import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'fs'
import { basename, join } from 'path'

import { compile } from './compile'
import { readForms } from './lisp'

/**
 * Compiles the Abuse scripts to TypeScript modules.
 *
 * Output goes to `src/lisp/generated/`, not `public/`: it is code, so it
 * should be typechecked and bundled with everything else rather than fetched
 * at runtime. Generated files are gitignored and rebuilt by `npm run assets`,
 * the same as the atlases - the repo holds Abuse's shipped scripts, not a
 * derivative of them.
 */

const SOURCE = 'assets/original/lisp'
const OUT = 'src/lisp/generated'

/**
 * Files that define behaviour. The rest of the tree is menus, netplay and the
 * editor, none of which we run - and every one of them drags in another
 * hundred hooks that exist only to serve it.
 */
const SKIP = /^(menu|netcfg|editor|chat|dev|sthelp|input|options)/

export function buildScripts(): { modules: number; functions: number; hooks: Map<string, number> } {
  rmSync(OUT, { recursive: true, force: true })
  mkdirSync(OUT, { recursive: true })

  const hooks = new Map<string, number>()
  /** `{ file, binding }` - `switch.lsp` cannot be imported as `switch`. */
  const modules: { file: string; binding: string }[] = []
  let functions = 0

  for (const file of readdirSync(SOURCE).sort()) {
    if (!file.endsWith('.lsp')) continue
    if (SKIP.test(file)) continue

    const name = basename(file, '.lsp')
    const result = compile(readForms(readFileSync(join(SOURCE, file), 'utf8')), `lisp/${file}`)
    if (result.functions.length === 0) continue

    writeFileSync(join(OUT, `${name}.ts`), result.code)
    modules.push({ file: name, binding: `m_${name.replace(/[^A-Za-z0-9_$]/g, '_')}` })
    functions += result.functions.length
    for (const hook of result.hooks) hooks.set(hook, (hooks.get(hook) ?? 0) + 1)
  }

  // One barrel, so the runtime can look a script function up by the name the
  // character's `ai_fun` gives - which is a string, not an import.
  const index =
    `// Generated by tools/scripts.ts. Do not edit.\n\n` +
    modules.map((m) => `import * as ${m.binding} from './${m.file}'`).join('\n') +
    `\n\n/** Every compiled script function, by its lisp name. */\n` +
    `/* eslint-disable */\n` +
    `export const SCRIPTS: Record<string, (...args: any[]) => any> = Object.assign(\n` +
    `  Object.create(null),\n` +
    modules.map((m) => `  ${m.binding},`).join('\n') +
    `\n)\n\n/** Runs every module's top-level forms once, in load order. */\n` +
    `export function loadScripts(): void {\n` +
    modules.map((m) => `  ${m.binding}.load()`).join('\n') +
    `\n}\n`
  writeFileSync(join(OUT, 'index.ts'), index)

  return { modules: modules.length, functions, hooks }
}

if (process.argv[1]?.endsWith('scripts.ts')) {
  const { modules, functions, hooks } = buildScripts()
  const missing = [...hooks].sort((a, b) => b[1] - a[1])
  console.log(`scripts: ${modules} modules, ${functions} functions, ${hooks.size} hooks referenced`)
  console.log(`  most used: ${missing.slice(0, 12).map(([n]) => n).join(' ')}`)
}
